### ISSUE TITLE
Jupyter kernel fails to start on ubuntu DLVM

### ISSUE THREAD

**Issue by KBaroni** [Azure/Batch-Scoring-Deep-Learning-Models-With-AKS#16]
Provisioned a new ubuntu DLVM because it has GPU support, followed setup instructions under the Readme, and verified required versions.   The _batchscoringdl_ kernel fails to start (restarts don't help).  Changing to a different kernel avoids the dead kernel but it won't execute the _dotenv_ cells. 
![deadkernel](https://user-images.githubusercontent.com/11684650/51272298-0532b780-1987-11e9-80f6-02d1d81f952c.jpg)

The problem seems to be a versioning problem with _prompt_toolkit_ (snip from the jupyter execution window:    _…from prompt_toolkit.formatted_text import PygmentsTokens
ModuleNotFoundError: No  module named ‘prompt_toolkit.formatted_text’_
after down-versioning ipython to 6.5, the notebook executed.  My concern is that during the down-versioning, a bunch of azure cli compatibility issues displayed so i'm not confident down-grading ipython is the right resolution - maybe just downgrading _prompt_toolkit_ is the right solution...?

**Comment by jiata** [comment]
@KBaroni - resolved. please see fix in readme. https://github.com/Azure/Batch-Scoring-Deep-Learning-Models-With-AKS#dlvm-setup
