### ISSUE TITLE
Service Principal permissions concern with 01_Setup notebook

### ISSUE THREAD

**Issue by KBaroni** [Azure/Batch-Scoring-Deep-Learning-Models-With-AKS#17]
Ran into in issue in the 01_setup notebook in the section for creating the Service Principal.  Added ```display(credentials``` to the credentials cell code to find out why the subsequent cells were failing.  The error indicates i don't have permissions to execute the RBAC operation.  The code may be assuming users who run the notebook have administrator level rights to the tenant or the subscription - which i do not have and it's likely that anyone running this with an enterprise subscription would also not have.  

Can this functionality be enabled without requiring elevated permissions for the person running the notebook?

**Comment by jiata** [comment]
remove service principal in 01_setup
