### ISSUE TITLE
Blobfuse section in 01_setup noteook failed/malformed .env file

### ISSUE THREAD

**Issue by KBaroni** [Azure/Batch-Scoring-Deep-Learning-Models-With-AKS#18]
The failure specifically occurred when trying to mount blob to the mount directory:  Failed to connect to the storage container. There might be something wrong about the storage config, please double check the storage account name, account key and container name. errno = 400.  After working with JS Tan, the root cause seems to be a mal-formed .env file.  Once the format of the .env file was corrected, the code worked. 

Not sure how the .env file became mal-formed.

**Comment by jiata** [comment]
closing. duplicate with #11
